routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Editing\PageRoutes;
use App\Http\Controllers\Frontend\Auth\SocialLoginController;

Auth::routes(['verify' => true]);

// Dynamic pages routes
app(PageRoutes::class)->routes();

Route::group(['namespace' => 'Backend', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'role:admin'], function () {
    Route::get('/', function () {
        return redirect('admin/dashboard');
    });
    Route::get('dashboard', 'DashboardController@index')->name('home');
    include_route_files(__DIR__ . '/backend/');
});

Route::group(['namespace' => 'Business', 'prefix' => 'cabinet/business', 'as' => 'business.', 'middleware' => 'role:user|admin'], function () {
    include_route_files(__DIR__ . '/business/');
});

Route::group(['namespace' => 'Cabinet', 'prefix' => 'cabinet', 'as' => 'cabinet.', 'middleware' => 'role:user|admin'], function () {
    Route::get('/', function () {
        return redirect('cabinet/dashboard');
    });
    Route::get('dashboard', 'DashboardController@index')->name('home');
    include_route_files(__DIR__ . '/cabinet/');
});

Route::group(['namespace' => 'Api', 'prefix' => 'api', 'as' => 'api.'], function () {
    Route::group(['namespace' => 'Backend', 'prefix' => 'backend', 'as' => 'backend.', 'middleware' => 'role:admin'], function () {
        include_route_files(__DIR__ . '/api/backend/');
    });
    Route::group(['namespace' => 'Frontend', 'prefix' => 'frontend', 'as' => 'frontend.'], function () {
        include_route_files(__DIR__ . '/api/frontend/');
    });
    Route::group(['namespace' => 'Business', 'prefix' => 'cabinet/business', 'as' => 'cabinet.', 'middleware' => 'role:user|admin'], function () {
        include_route_files(__DIR__ . '/api/business/');
    });
    Route::group(['namespace' => 'Cabinet', 'prefix' => 'cabinet', 'as' => 'cabinet.', 'middleware' => 'role:user|admin'], function () {
        include_route_files(__DIR__ . '/api/cabinet/');
    });
});

// Socialite Routes
Route::get('login/{provider}', [SocialLoginController::class, 'login'])->name('social.login');
Route::get('login/{provider}/callback', [SocialLoginController::class, 'login']);

Route::get('/home', function () {
    return redirect('/');
});
require __DIR__ . '/users/users.php';
require __DIR__ . '/roles/roles.php';
require __DIR__ . '/roles/permissions.php';
require __DIR__ . '/modules/modules.php';

Route::group(['namespace' => 'Frontend', 'as' => 'frontend.'], function () {
    require __DIR__ . '/frontend/event.php';
    require __DIR__ . '/frontend/company.php';
    require __DIR__ . '/frontend/city.php';
});

app/Comment.php
<?php

namespace App;

use App\Events\Comment\Created;
use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $fillable = ['text', 'published'];

    protected $casts = [
        'published' => 'boolean'
    ];

    protected $dispatchesEvents = [
        'created' => Created::class
    ];

    public function commented()
    {
        return $this->morphTo();
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function answers()
    {
        return $this->hasMany(CommentAnswer::class, 'comment_id');
    }

    public function getStarAttribute()
    {
        return $this->commented->user_rating ? $this->commented->user_rating->star : null;
    }

    public function getRecAttribute()
    {
        return $this->commented->user_recommendation ? $this->commented->user_recommendation->bool : null;
    }
}

app/Slide.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Storage;

class Slide extends Model
{
    protected $fillable = ['name', 'summary', 'button'];

    public function image()
    {
        return $this->belongsTo(Download::class, 'image_id');
    }

    public function selection()
    {
        return $this->belongsTo(Selection::class);
    }

    public function city()
    {
        return $this->belongsTo(City::class);
    }

    public function getImageUrlAttribute()
    {
        if (empty($this->image)) {
            return 'http://via.placeholder.com/2880x886';
        }
        return Storage::url($this->image->path);
    }

    public function getTypeAttribute()
    {
        $events = $this->selection->events;
        $companies = $this->selection->companies;

        if ($events && $events->count() > 0) {
            if ($events->count() == 1) {
                return 'event-single';
            }
            return 'events';
        }
        if ($companies && $companies->count() > 0) {
            if ($companies->count() == 1) {
                return 'company-single';
            }
            return 'companies';
        }
        return null;
    }

    public function getItemsAttribute()
    {
        if ($this->type == 'event-single') {
            return $this->selection->events[0];
        } else if ($this->type == 'events') {
            return $this->selection->events->implode('id', ',');
        } else if ($this->type == 'company-single') {
            return $this->selection->companies[0];
        } else if ($this->type == 'companies') {
            return $this->selection->companies->implode('id', ',');
        }
        return null;
    }

    public function getUrlAttribute()
    {
        if ($this->type == 'event-single') {
            return route('frontend.event.show', $this->items);
        } else if ($this->type == 'events') {
            return route('frontend.event.index', array_merge($this->selection->params, ['items' => $this->items]));
        } else if ($this->type == 'company-single') {
            return route('frontend.company.show', $this->items);
        } else if ($this->type == 'companies') {
            return route('frontend.company.index', array_merge($this->selection->params, ['items' => $this->items]));
        }
        return '/';
    }
}

app/Tile.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tile extends Model
{
    protected $fillable = ['name', 'summary'];

    public function selection()
    {
        return $this->belongsTo(Selection::class);
    }

    public function city()
    {
        return $this->belongsTo(City::class);
    }

    public function getTypeAttribute()
    {
        $events = $this->selection->events;
        $companies = $this->selection->companies;

        if (empty($events) && empty($companies)) {
            return 'zaebalo';
        }
        if ($events && $events->count() > 0) {
            if ($events->count() == 1) {
                return 'event-single';
            }
            return 'events';
        }
        if ($companies && $companies->count() > 0) {
            if ($companies->count() == 1) {
                return 'company-single';
            }
            return 'companies';
        }
        return null;
    }

    public function getItemsAttribute()
    {
        if ($this->type == 'event-single') {
            return $this->selection->events[0];
        } else if ($this->type == 'events') {
            return $this->selection->events->implode('id', ',');
        } else if ($this->type == 'company-single') {
            return $this->selection->companies[0];
        } else if ($this->type == 'companies') {
            return $this->selection->companies->implode('id', ',');
        }
        return null;
    }

    public function getUrlAttribute()
    {
        if ($this->type == 'event-single') {
            return route('frontend.event.show', $this->items);
        } else if ($this->type == 'events') {
            return route('frontend.event.index', array_merge($this->selection->params, ['items' => $this->items]));
        } else if ($this->type == 'company-single') {
            return route('frontend.company.show', $this->items);
        } else if ($this->type == 'companies') {
            return route('frontend.company.index', array_merge($this->selection->params, ['items' => $this->items]));
        }
        return '/';
    }
}

app/Http/Controllers/Api/Backend/Company/Address/AddressController.php
<?php

namespace App\Http\Controllers\Api\Backend\Company\Address;

use App\Address;
use App\City;
use App\Company;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AddressController extends Controller
{
    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param Company $company
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request, Company $company)
    {
        $validData = $this->validate($request, [
            'city.name' => 'required|string',
            'city.lat' => 'required|numeric',
            'city.long' => 'required|numeric',
            'address' => 'required|string',
            'phone' => 'nullable|string',
            'work' => 'nullable|string',
            'lat' => 'required|numeric',
            'long' => 'required|numeric',
            'site' => 'string'
        ]);

        // Вытаскиваем по названию город либо создаем новый
        $city = City::firstOrCreate([
            'name' => $validData['city']['name']
        ], [
            'lat' => $validData['city']['lat'],
            'long' => $validData['city']['long']
        ]);

        // создаем адрес, присваиваем компанию и город и после сохраняем
        $address = Address::make([
            'address' => $validData['address'],
            'phone' => $validData['phone'] ?? null,
            'work' => $validData['work'] ?? null,
            'site' => $validData['site'] ?? null,
            'lat' => $validData['lat'],
            'long' => $validData['long']
        ]);

        $address->company()->associate($company);
        $address->city()->associate($city);

        $address->save();

        return json_encode($address);
    }

    /**
     * Display the specified resource.
     *
     * @param Address $address
     * @return Address
     */
    public function show(Company $company, Address $address)
    {
        return $address->load([
            'city'
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param Company $company
     * @param Address $address
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(Request $request, Company $company, Address $address)
    {
        $validData = $this->validate($request, [
            'city.name' => 'required|string',
            'city.lat' => 'required|numeric',
            'city.long' => 'required|numeric',
            'address' => 'required|string',
            'phone' => 'nullable|string',
            'work' => 'nullable|string',
            'lat' => 'required|numeric',
            'long' => 'required|numeric',
            'site' => 'string'
        ]);

        // Вытаскиваем по названию город либо создаем новый
        $city = City::firstOrCreate([
            'name' => $validData['city']['name']
        ], [
            'lat' => $validData['city']['lat'],
            'long' => $validData['city']['long']
        ]);

        $address->update([
            'address' => $validData['address'],
            'phone' => $validData['phone'] ?? null,
            'work' => $validData['work'] ?? null,
            'site' => $validData['site'] ?? null,
            'lat' => $validData['lat'],
            'long' => $validData['long']
        ]);

        $address->city()->associate($city);
        $address->save();

        return json_encode($address);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Company $company
     * @param Address $address
     * @return int
     * @throws \Exception
     */
    public function destroy(Company $company, Address $address)
    {
        return json_encode($address->delete());
    }
}

app/Http/Controllers/Api/Backend/Company/Category/CategoryController.php
<?php

namespace App\Http\Controllers\Api\Backend\Company\Category;

use App\CompanyCategory as Category;
use App\Download;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Contracts\Pagination\LengthAwarePaginator
     */
    public function filter(Request $request)
    {
        $query = Category::query();

        if ($request->search) {
            $query->where('name', 'LIKE', '%' . $request->search . '%');
        }

        $items = $query->orderBy($request->input('orderBy.column'), $request->input('orderBy.direction'))
            ->paginate($request->input('pagination.per_page'));

        return $items;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $validData = $this->validate($request, [
            'name' => 'required|string|unique:event_categories,name',
            'slug' => 'nullable|string|unique:event_categories,slug',
            'background.id' => 'required|exists:downloads,id',
        ]);

        $category = Category::make($validData);
        $category->background()->associate(Download::find($validData['background']['id']));
        $category->save();

        return $category;
    }

    /**
     * Display the specified resource.
     *
     * @param Category $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        return $category;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param Category $category
     * @return Category
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(Request $request, Category $category)
    {
        $validData = $this->validate($request, [
            'name' => 'required|string|unique:event_categories,name,' . $request->id,
            'slug' => 'nullable|string|unique:event_categories,slug,' . $request->id,
            'background.id' => 'required|exists:downloads,id',
        ]);

        $category->fill($validData);
        $category->background()->associate(Download::find($validData['background']['id']));
        $category->save();

        return $category;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Category $category
     * @return int
     */
    public function destroy(Category $category)
    {
        return Category::destroy($category->id);
    }

    public function all()
    {
        return Category::orderBy('name')->get();
    }
}

app/Http/Controllers/Api/Backend/Company/GalleryItem/GalleryItemController.php
<?php

namespace App\Http\Controllers\Api\Backend\Company\GalleryItem;

use App\Download;
use App\Company;
use App\Http\Controllers\Controller;
use App\Video;
use Illuminate\Http\Request;
use Storage;

class GalleryItemController extends Controller
{
    /**
     * @param Request $request
     * @param Company $company
     * @return
     * @throws \Illuminate\Validation\ValidationException
     */
    public function video(Request $request, Company $company)
    {
        $validData = $this->validate($request, [
            'link' => 'required|string'
        ]);

        $video = Video::create($validData);

        return $video->company_gallery_items()->save(
            $company->gallery_items()->make([
                'sort' => 9999
            ])
        )->load('attachable');
    }

    /**
     * @param Request $request
     * @param Company $company
     * @return
     */
    public function photo(Request $request, Company $company)
    {
        $photos = [];
        foreach ($request->files as $key => $files) {
            if ($key == 'files') {
                foreach ($files as $file) {
                    // так сделал, чтобы нормально сохранял svg файлы и другие
                    $path = Storage::putFileAs('uploads', $file, time() . rand(1000, 9999) . '.' . $file->getClientOriginalExtension());

                    $photo = Download::create([
                        'path' => $path,
                        'original_name' => $file->getClientOriginalName(),
                        'mime_type' => $file->getMimeType(),
                        'size' => $file->getSize()
                    ]);

                    $photos[] = $photo->company_gallery_items()->save(
                        $company->gallery_items()->make([
                            'sort' => 9999
                        ])
                    )->load('attachable');
                }
            }
        }

        return $photos;
    }
}

app/Http/Controllers/Api/Cabinet/Company/Category/CategoryController.php
<?php

namespace App\Http\Controllers\Api\Cabinet\Company\Category;

use App\CompanyCategory as Category;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    /**
     * Display the specified resource.
     *
     * @param Category $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        return $category;
    }

    public function all()
    {
        return Category::orderBy('name')->get();
    }
}

resources/views/frontend/city/company/category/show.blade.php
@extends('frontend.layouts.app')

@section('header')
    @include('frontend.includes.headers.company-category')
@endsection

@push('after-scripts')
    <script>
        $('.companies-container').infiniteScroll({
            path: '.pagination__next',
            append: '.company-item',
            button: '.view-more-button',
            // using button, disable loading on scroll
            scrollThreshold: false,
            // status: '.page-load-status',
        });
    </script>
@endpush

@section('title', 'Каталог компаний' . (empty($category) ? '' : ' - ' . $category->name))
@section('description', 'Каталог компаний' . (empty($category) ? '' : ' - ' . $category->name))

@section('content')
    <div class="container-fluid search-panel">
        <div class="container minus-15">
            <div class="row">
                <div class="col-md-12">
                    <div class="events-block company-block">
                        <div class="row companies-container bootfix-row">
                            @foreach($companies as $key => $company)
                                <div class="col-lg-3 col-md-6 col-sm-6 company-item bootfix-col">
                                    <div class="search-panel__company-block">
                                        <img src="{{ $company->image_url }}"/>
                                        <a href="{{ route('frontend.company.show', $company) }}">
                                            <div class="events-block__empty"></div>
                                        </a>
                                        <a href="{{ route('frontend.city.company.category.show', [$city, empty($category) ? $company->categories[0] : $category]) }}">
                                            <div class="search-panel__company-group">
                                                {{ empty($category) ? $company->categories[0]->name : $category->name }}
                                            </div>
                                        </a>
                                        <company-bookmark :company="{{ json_encode($company->only('slug')) }}"
                                                          :status="{{ json_encode(Auth()->user() ? Auth()->user()->favorite_companies->contains('id', $company->id) : false) }}"></company-bookmark>
                                        <div class="search-panel__company-text">
                                            <div class="search-panel__company-title">{{ $company->name }}</div>
                                            <div class="search-panel__company-place">{{ $company->addresses->count() > 0 ? $company->addresses[0]->address : '' }} {{ $company->addresses->count() > 1 ? ' и еще ' . ($company->addresses->count() - 1) : '' }}</div>
                                            <div class="search-panel__company-badges">
                                                <img src="/images/icons/thumb-up-black.svg"/>
                                                <span>{{ $company->rec }}</span>
                                                <img class="star" src="/images/icons/star.svg"/>
                                                <span>{{ round($company->star, 1) }}</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                @if(($key + 1) == 8)
                                    @if($companyListOnePlace->activeBanners->count() > 0)
                                        <div id="owl-company-list-1" class="col-md-12 text-center ad bootfix-col owl-carousel owl-theme">
                                            @foreach($companyListOnePlace->activeBanners as $activeBanner)
                                                <a href="{{ $activeBanner->link }}" target="_blank">
                                                    <img src="{{ $activeBanner->download->url }}"/>
                                                </a>
                                            @endforeach
                                        </div>
                                    @endif
                                @elseif(($key + 1) == 16)
                                    @if($companyListSecondPlace->activeBanners->count() > 0)
                                        <div id="owl-company-list-2" class="col-md-12 text-center ad bootfix-col owl-carousel owl-theme">
                                            @foreach($companyListSecondPlace->activeBanners as $activeBanner)
                                                <a href="{{ $activeBanner->link }}" target="_blank">
                                                    <img src="{{ $activeBanner->download->url }}"/>
                                                </a>
                                            @endforeach
                                        </div>
                                    @endif
                                @elseif(($key + 1) == 32)
                                    @if($companyListTreePlace->activeBanners->count() > 0)
                                        <div id="owl-company-list-3" class="col-md-12 text-center ad bootfix-col owl-carousel owl-theme">
                                            @foreach($companyListTreePlace->activeBanners as $activeBanner)
                                                <a href="{{ $activeBanner->link }}" target="_blank">
                                                    <img src="{{ $activeBanner->download->url }}"/>
                                                </a>
                                            @endforeach
                                        </div>
                                    @endif
                                @endif
                            @endforeach
                        </div>
                        <div class="row">
                            <div class="col-md-12 bot-panel">
                                <div class="row">
                                    <div class="col-lg-6 col-sm-8">
                                        {{ $companies->links('frontend.includes.pagination', ['paginator' => $companies]) }}
                                    </div>
                                    <div class="col-lg-6 col-sm-4 show-more">
                                        @if ($companies->lastPage() != $companies->currentPage())
                                            <a href="">
                                                <div class="view-more-button">Показать еще</div>
                                            </a>
                                        @endif
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12 direct">
                                <img src="/images/ad.png"/>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection